#!/usr/bin/env python3
"""golive.core.clone_site — clone a web page for republishing.

Flow: classify URL -> fetch (with resource inlining) -> migration analysis
-> patch (font mirrors / sensitive-config scrubbing / backend rewrite)
-> return the patched HTML (or downloaded zip path) to the caller.

This module is UI-light: it prints the analysis report but leaves the
publish / save decision to the CLI (``golive clone <url>``).

Public API:
  run_clone(url, use_headless=False, analyze_only=False,
            backend_origin="", skip_backend_rewrite=False,
            skip_inline=False) -> dict
      {
        "html": str,            # patched HTML ("" when zip)
        "source_zip": str|None, # downloaded zip path
        "name": str,            # suggested site name (from <title>)
        "notes": list[str],
        "analysis": dict,
        "sensitive_findings": list,
        "clone_info": dict|None,
      }
"""

from __future__ import annotations

import datetime
import re
import sys
import threading
from pathlib import Path
from urllib.parse import urlparse

from golive.core import clone_analyzer as analyzer
from golive.core import clone_fetcher as fetcher
from golive.core import clone_patcher as patcher
from golive.i18n import t as _t

FETCH_TIMEOUT = 90  # seconds — overall fetch + inline budget


# ── helpers ──────────────────────────────────────────────────────────────────

def _separator():
    print("━" * 38)


def domain_from_url(url: str) -> str:
    """Extract a filename-safe domain fragment from a URL."""
    try:
        parsed = urlparse(url)
        host = parsed.netloc or parsed.path
        host = host.split(":")[0].replace("www.", "")
        safe = "".join(c if c.isalnum() or c in "-." else "_" for c in host)
        return safe[:40] or "site"
    except Exception:
        return "site"


def _timestamp() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def save_to_local(html: str, url: str, dest_dir: Path = None) -> Path:
    """Save cloned HTML into dest_dir (default CWD). Returns the file path."""
    filename = f"cloned_{domain_from_url(url)}_{_timestamp()}.html"
    out_path = (dest_dir or Path.cwd()) / filename
    out_path.write_text(html, encoding="utf-8")
    return out_path


# ── model-code scrubbing (compat with intranet-generated pages) ─────────────

def scrub_model_code(html: str) -> tuple[str, list[str]]:
    """Replace any residual data-layer modelCode literals with placeholders.

    Pages generated by the intranet edition may embed `modelCode: 'xxx'`
    configs. A cloned copy must not reuse the original site's modelCode
    (data would cross-pollute), so every hit becomes __PLACEHOLDER_MODEL_CODE__.
    Returns (patched_html, found_codes).
    """
    pattern = re.compile(
        r"((?:^|[{,;\n])\s*(?:MODEL_CODE\s*=|modelCode\s*[=:])\s*['\"]?\s*)"
        r"([A-Za-z0-9_]+)(\s*['\"]?\s*)",
        re.IGNORECASE | re.MULTILINE,
    )
    matches = list(pattern.finditer(html))
    found: list[str] = []
    result = html
    for m in reversed(matches):
        original = m.group(2)
        if original.startswith("__PLACEHOLDER"):
            continue
        if original not in found:
            found.append(original)
        result = (result[:m.start()] + m.group(1)
                  + "__PLACEHOLDER_MODEL_CODE__" + m.group(3) + result[m.end():])
    found.reverse()
    return result, found


# ── report printing ──────────────────────────────────────────────────────────

def print_report(url: str, strategy: str, notes: list, analysis: dict):
    print()
    print(_t("clone_site.report_title"))
    _separator()
    print(_t("clone_site.source", url=url))
    print(_t("clone_site.strategy", strategy=strategy))
    score = analysis.get("score", "?")
    print(_t("clone_site.score", score=score))
    summary = analysis.get("summary", "")
    if summary:
        print(_t("clone_site.summary", summary=summary))
    api_deps = analysis.get("api_deps", [])
    if api_deps:
        print(_t("clone_site.api_deps_header", count=len(api_deps)))
        for dep in api_deps[:8]:
            print(f"  · {dep}")
        if len(api_deps) > 8:
            print(_t("clone_site.api_deps_more", count=len(api_deps)))
    for w in analysis.get("warnings", []):
        print(f"⚠️  {w}")
    for n in notes:
        print(f"  {n}")
    _separator()


def print_sensitive_report(findings: list[dict]):
    print(_t("clone_site.sensitive_title"))
    _separator()
    for finding in findings:
        print(_t("clone_site.sensitive_module", label=finding.get('module_label', '?')))
        for f in finding.get("scrubbed_fields", []):
            print(_t("clone_site.sensitive_replaced", name=f.get('name')))
    print(_t("clone_site.sensitive_hint"))
    _separator()


# ── main flow ────────────────────────────────────────────────────────────────

def run_clone(
    url: str,
    use_headless: bool = False,
    analyze_only: bool = False,
    backend_origin: str = "",
    skip_backend_rewrite: bool = False,
) -> dict:
    """Clone a page. Returns a result dict (see module docstring).

    Raises SystemExit on unrecoverable fetch errors.
    """
    url = url.strip()
    print()
    print(_t("clone_site.banner"))
    _separator()
    print(_t("clone_site.target_url", url=url))
    print()

    # Step 1: classify
    print(_t("clone_site.analyzing_url"))
    url_type = fetcher.classify_url(url)
    print(_t("clone_site.url_type", url_type=url_type))
    print()

    clone_info = None
    try:
        clone_info = fetcher.build_clone_info(url)
    except Exception:
        pass

    # Step 2: fetch (in a daemon thread with a hard timeout)
    print(_t("clone_site.fetching", headless_note=_t("clone_site.fetching_headless_note") if use_headless else ""))
    result_box: list = []
    error_box: list = []

    def _fetch_worker():
        try:
            result_box.append(fetcher.fetch_site(
                url, url_type,
                use_headless=use_headless,
                skip_inline=analyze_only,
            ))
        except Exception as e:  # noqa: BLE001
            error_box.append(e)

    t = threading.Thread(target=_fetch_worker, daemon=True)
    t.start()
    t.join(timeout=FETCH_TIMEOUT)

    if t.is_alive():
        print(_t("clone_site.fetch_timeout", timeout=FETCH_TIMEOUT), file=sys.stderr)
        print(_t("clone_site.fetch_timeout_hint_1"), file=sys.stderr)
        print(_t("clone_site.fetch_timeout_hint_2"), file=sys.stderr)
        print(_t("clone_site.fetch_timeout_hint_3"), file=sys.stderr)
        sys.exit(1)
    if error_box:
        print(_t("clone_site.fetch_failed", error=error_box[0]), file=sys.stderr)
        sys.exit(1)

    fetch_result = result_box[0]
    html_content = fetch_result.get("html", "")
    strategy_used = fetch_result.get("strategy_used", "unknown")
    notes = fetch_result.get("notes", [])
    source_zip = fetch_result.get("source_zip")

    print(_t("clone_site.strategy_label", strategy=strategy_used))
    if not html_content and not source_zip:
        print()
        print(_t("clone_site.no_content"))
        print(_t("clone_site.no_content_reason_1"))
        print(_t("clone_site.no_content_reason_2"))
        print()
        print(_t("clone_site.no_content_hint"))
        sys.exit(1)
    if html_content:
        print(_t("clone_site.content_size", size=len(html_content)))
    print()

    # zip fast-path — no HTML analysis possible
    if source_zip:
        return {
            "html": "",
            "source_zip": source_zip,
            "name": _t("clone_site.cloned_site_name", domain=domain_from_url(url)),
            "notes": notes,
            "analysis": {},
            "sensitive_findings": [],
            "clone_info": clone_info,
        }

    # Step 3: migration analysis
    print(_t("clone_site.analyzing"))
    try:
        analysis = analyzer.analyze(html_content, base_url=url)
    except Exception as e:  # noqa: BLE001
        print(_t("clone_site.analysis_failed", error=e), file=sys.stderr)
        analysis = {"api_deps": [], "font_issues": [], "localstorage_usage": False,
                    "score": 100, "warnings": [], "summary": ""}

    print_report(url, strategy_used, notes, analysis)

    if analyze_only:
        return {
            "html": html_content,
            "source_zip": None,
            "name": "",
            "notes": notes,
            "analysis": analysis,
            "sensitive_findings": [],
            "clone_info": clone_info,
        }

    # Step 4: backend rewrite decision (non-interactive: arg or inferred)
    backend_issues = analysis.get("backend_issues", {})
    has_backend_issues = bool(backend_issues.get("relative") or backend_issues.get("localhost"))
    resolved_backend_origin = ""
    if not skip_backend_rewrite and has_backend_issues:
        if backend_origin:
            resolved_backend_origin = backend_origin.rstrip("/")
            print(_t("clone_site.backend_rewrite_specified", origin=resolved_backend_origin))
        elif backend_issues.get("inferred_origin"):
            resolved_backend_origin = backend_issues["inferred_origin"]
            print(_t("clone_site.backend_rewrite_inferred", origin=resolved_backend_origin))
        else:
            print(_t("clone_site.backend_rewrite_cannot_infer"))
    elif skip_backend_rewrite and has_backend_issues:
        print(_t("clone_site.backend_rewrite_skipped"))

    # Step 5: patch
    print()
    print(_t("clone_site.patching"))
    sensitive_findings: list = []
    try:
        patched_html, sensitive_findings, backend_summary = patcher.patch(
            html_content, notes, backend_origin=resolved_backend_origin
        )
    except Exception as e:  # noqa: BLE001
        print(_t("clone_site.patch_failed", error=e), file=sys.stderr)
        patched_html = html_content
        backend_summary = {}
        print(_t("clone_site.patch_warning"), file=sys.stderr)

    if backend_summary.get("relative_count") or backend_summary.get("localhost_count"):
        print(_t("clone_site.rewrite_summary",
                 rel_count=backend_summary.get('relative_count', 0),
                 loc_count=backend_summary.get('localhost_count', 0),
                 origin=resolved_backend_origin))

    # Step 6: scrub residual modelCode
    patched_html, leaked = scrub_model_code(patched_html)
    if leaked:
        print(_t("clone_site.model_code_leaked", codes=", ".join(leaked)))

    if sensitive_findings:
        print()
        print_sensitive_report(sensitive_findings)

    # suggested name from <title>
    name = ""
    m = re.search(r"<title[^>]*>([^<]+)</title>", patched_html, re.IGNORECASE)
    if m:
        name = m.group(1).strip()[:60]
    if not name:
        name = _t("clone_site.cloned_site_name", domain=domain_from_url(url))

    return {
        "html": patched_html,
        "source_zip": None,
        "name": name,
        "notes": notes,
        "analysis": analysis,
        "sensitive_findings": sensitive_findings,
        "clone_info": clone_info,
    }
