#!/usr/bin/env python3
"""golive.core.clone_site — clone a web page for republishing.

Flow: classify URL -> fetch (with resource inlining) -> migration analysis
-> patch (font mirrors / sensitive-config scrubbing / backend rewrite)
-> return the patched HTML (or downloaded zip path) to the caller.

This module is UI-light: it prints the analysis report but leaves the
publish / save decision to the CLI (``golive clone <url>``).

Public API:
  run_clone(url, use_headless=False, analyze_only=False,
            backend_origin="", skip_backend_rewrite=False,
            skip_inline=False) -> dict
      {
        "html": str,            # patched HTML ("" when zip)
        "source_zip": str|None, # downloaded zip path
        "name": str,            # suggested site name (from <title>)
        "notes": list[str],
        "analysis": dict,
        "sensitive_findings": list,
        "clone_info": dict|None,
      }
"""

from __future__ import annotations

import datetime
import re
import sys
import threading
from pathlib import Path
from urllib.parse import urlparse

from golive.core import clone_analyzer as analyzer
from golive.core import clone_fetcher as fetcher
from golive.core import clone_patcher as patcher

FETCH_TIMEOUT = 90  # seconds — overall fetch + inline budget


# ── helpers ──────────────────────────────────────────────────────────────────

def _separator():
    print("━" * 38)


def domain_from_url(url: str) -> str:
    """Extract a filename-safe domain fragment from a URL."""
    try:
        parsed = urlparse(url)
        host = parsed.netloc or parsed.path
        host = host.split(":")[0].replace("www.", "")
        safe = "".join(c if c.isalnum() or c in "-." else "_" for c in host)
        return safe[:40] or "site"
    except Exception:
        return "site"


def _timestamp() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def save_to_local(html: str, url: str, dest_dir: Path = None) -> Path:
    """Save cloned HTML into dest_dir (default CWD). Returns the file path."""
    filename = f"cloned_{domain_from_url(url)}_{_timestamp()}.html"
    out_path = (dest_dir or Path.cwd()) / filename
    out_path.write_text(html, encoding="utf-8")
    return out_path


# ── model-code scrubbing (compat with intranet-generated pages) ─────────────

def scrub_model_code(html: str) -> tuple[str, list[str]]:
    """Replace any residual data-layer modelCode literals with placeholders.

    Pages generated by the intranet edition may embed `modelCode: 'xxx'`
    configs. A cloned copy must not reuse the original site's modelCode
    (data would cross-pollute), so every hit becomes __PLACEHOLDER_MODEL_CODE__.
    Returns (patched_html, found_codes).
    """
    pattern = re.compile(
        r"((?:^|[{,;\n])\s*(?:MODEL_CODE\s*=|modelCode\s*[=:])\s*['\"]?\s*)"
        r"([A-Za-z0-9_]+)(\s*['\"]?\s*)",
        re.IGNORECASE | re.MULTILINE,
    )
    matches = list(pattern.finditer(html))
    found: list[str] = []
    result = html
    for m in reversed(matches):
        original = m.group(2)
        if original.startswith("__PLACEHOLDER"):
            continue
        if original not in found:
            found.append(original)
        result = (result[:m.start()] + m.group(1)
                  + "__PLACEHOLDER_MODEL_CODE__" + m.group(3) + result[m.end():])
    found.reverse()
    return result, found


# ── report printing ──────────────────────────────────────────────────────────

def print_report(url: str, strategy: str, notes: list, analysis: dict):
    print()
    print("📋 迁移性分析报告")
    _separator()
    print(f"来源: {url}")
    print(f"策略: {strategy}")
    score = analysis.get("score", "?")
    print(f"迁移评分: {score}/100")
    summary = analysis.get("summary", "")
    if summary:
        print(f"摘要: {summary}")
    api_deps = analysis.get("api_deps", [])
    if api_deps:
        print(f"\nAPI 依赖（{len(api_deps)} 处，发布后可能无法访问）：")
        for dep in api_deps[:8]:
            print(f"  · {dep}")
        if len(api_deps) > 8:
            print(f"  · ... 等共 {len(api_deps)} 处")
    for w in analysis.get("warnings", []):
        print(f"⚠️  {w}")
    for n in notes:
        print(f"  {n}")
    _separator()


def print_sensitive_report(findings: list[dict]):
    print("🔒 敏感配置清理报告")
    _separator()
    for finding in findings:
        print(f"模块: {finding.get('module_label', '?')}")
        for f in finding.get("scrubbed_fields", []):
            print(f"  · {f.get('name')} → 已替换为占位符")
    print("提示：发布前请搜索 __PLACEHOLDER_ 并按需填写真实配置。")
    _separator()


# ── main flow ────────────────────────────────────────────────────────────────

def run_clone(
    url: str,
    use_headless: bool = False,
    analyze_only: bool = False,
    backend_origin: str = "",
    skip_backend_rewrite: bool = False,
) -> dict:
    """Clone a page. Returns a result dict (see module docstring).

    Raises SystemExit on unrecoverable fetch errors.
    """
    url = url.strip()
    print()
    print("🌐 golive 一键拷贝")
    _separator()
    print(f"目标 URL: {url}")
    print()

    # Step 1: classify
    print("🔍 正在分析 URL 类型...")
    url_type = fetcher.classify_url(url)
    print(f"   类型: {url_type}")
    print()

    clone_info = None
    try:
        clone_info = fetcher.build_clone_info(url)
    except Exception:
        pass

    # Step 2: fetch (in a daemon thread with a hard timeout)
    print(f"📥 正在抓取页面内容{'（无头浏览器模式）' if use_headless else ''}...")
    result_box: list = []
    error_box: list = []

    def _fetch_worker():
        try:
            result_box.append(fetcher.fetch_site(
                url, url_type,
                use_headless=use_headless,
                skip_inline=analyze_only,
            ))
        except Exception as e:  # noqa: BLE001
            error_box.append(e)

    t = threading.Thread(target=_fetch_worker, daemon=True)
    t.start()
    t.join(timeout=FETCH_TIMEOUT)

    if t.is_alive():
        print(f"\n⏱️  抓取超时（>{FETCH_TIMEOUT}s）。", file=sys.stderr)
        print("   页面资源可能过多，建议：", file=sys.stderr)
        print("   1. 在浏览器打开页面 → Ctrl+S 保存 HTML → golive publish 该文件", file=sys.stderr)
        print("   2. 或使用 --headless 参数（无头浏览器模式）重试", file=sys.stderr)
        sys.exit(1)
    if error_box:
        print(f"❌ 页面抓取失败: {error_box[0]}", file=sys.stderr)
        sys.exit(1)

    fetch_result = result_box[0]
    html_content = fetch_result.get("html", "")
    strategy_used = fetch_result.get("strategy_used", "未知")
    notes = fetch_result.get("notes", [])
    source_zip = fetch_result.get("source_zip")

    print(f"   策略: {strategy_used}")
    if not html_content and not source_zip:
        print()
        print("❌ 未能获取到页面内容。可能原因：")
        print("   • 网络不可达 / 需要登录")
        print("   • 页面由 JS 动态渲染（纯 requests 拿不到内容）")
        print()
        print("   💡 建议：在浏览器打开页面 → Ctrl+S 保存 HTML → golive publish 该文件")
        sys.exit(1)
    if html_content:
        print(f"   内容大小: {len(html_content):,} 字节")
    print()

    # zip fast-path — no HTML analysis possible
    if source_zip:
        return {
            "html": "",
            "source_zip": source_zip,
            "name": f"克隆站点 {domain_from_url(url)}",
            "notes": notes,
            "analysis": {},
            "sensitive_findings": [],
            "clone_info": clone_info,
        }

    # Step 3: migration analysis
    print("🔬 正在进行迁移性分析...")
    try:
        analysis = analyzer.analyze(html_content, base_url=url)
    except Exception as e:  # noqa: BLE001
        print(f"⚠️  分析失败（将跳过分析继续流程）: {e}", file=sys.stderr)
        analysis = {"api_deps": [], "font_issues": [], "localstorage_usage": False,
                    "score": 100, "warnings": [], "summary": "分析不可用"}

    print_report(url, strategy_used, notes, analysis)

    if analyze_only:
        return {
            "html": html_content,
            "source_zip": None,
            "name": "",
            "notes": notes,
            "analysis": analysis,
            "sensitive_findings": [],
            "clone_info": clone_info,
        }

    # Step 4: backend rewrite decision (non-interactive: arg or inferred)
    backend_issues = analysis.get("backend_issues", {})
    has_backend_issues = bool(backend_issues.get("relative") or backend_issues.get("localhost"))
    resolved_backend_origin = ""
    if not skip_backend_rewrite and has_backend_issues:
        if backend_origin:
            resolved_backend_origin = backend_origin.rstrip("/")
            print(f"🔧 后端接口重写: 使用指定地址 {resolved_backend_origin}")
        elif backend_issues.get("inferred_origin"):
            resolved_backend_origin = backend_issues["inferred_origin"]
            print(f"🔧 后端接口重写: 自动推断原始服务地址 → {resolved_backend_origin}")
        else:
            print("⚠️  检测到后端接口依赖，但无法推断原始服务地址；"
                  "可通过 --backend-origin 指定。本次保持原样。")
    elif skip_backend_rewrite and has_backend_issues:
        print("⚠️  [--skip-backend-rewrite] 已跳过后端接口重写，接口调用可能失败。")

    # Step 5: patch
    print()
    print("🔧 正在修补 HTML（字体替换 / 敏感配置脱敏等）...")
    sensitive_findings: list = []
    try:
        patched_html, sensitive_findings, backend_summary = patcher.patch(
            html_content, notes, backend_origin=resolved_backend_origin
        )
    except Exception as e:  # noqa: BLE001
        print(f"⚠️  修补失败（将使用原始 HTML）: {e}", file=sys.stderr)
        patched_html = html_content
        backend_summary = {}
        print("⚠️  HTML 修补异常，敏感配置脱敏可能未完成，请手动检查后再发布。", file=sys.stderr)

    if backend_summary.get("relative_count") or backend_summary.get("localhost_count"):
        print(f"   ✅ 已重写接口：相对路径 {backend_summary.get('relative_count', 0)} 处"
              f" + localhost {backend_summary.get('localhost_count', 0)} 处"
              f" → {resolved_backend_origin}")

    # Step 6: scrub residual modelCode
    patched_html, leaked = scrub_model_code(patched_html)
    if leaked:
        print(f"   ⚠️  检测到残留 modelCode（{', '.join(leaked)}），已替换为占位符。")

    if sensitive_findings:
        print()
        print_sensitive_report(sensitive_findings)

    # suggested name from <title>
    name = ""
    m = re.search(r"<title[^>]*>([^<]+)</title>", patched_html, re.IGNORECASE)
    if m:
        name = m.group(1).strip()[:60]
    if not name:
        name = f"克隆站点 {domain_from_url(url)}"

    return {
        "html": patched_html,
        "source_zip": None,
        "name": name,
        "notes": notes,
        "analysis": analysis,
        "sensitive_findings": sensitive_findings,
        "clone_info": clone_info,
    }
